// Days 2-6 stops migration
// Run: SUPABASE_URL=... SUPABASE_ANON_KEY=... node supabase/migrate_days2to6.js

const { createClient } = require('@supabase/supabase-js');
const supabase = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_ANON_KEY);

const TRIP_ID = '6b14589b-db99-4f64-be6d-ccb760e31c57';

// DAY 2 — Slieve League Day — Donegal
const DAY2_STOPS = [
  {"pos": 0, "name": "Wake Up", "emoji": "☀️", "time_label": "5:40 AM", "duration_minutes": null, "drive_override_minutes": null, "lat": 54.22781, "lng": -8.35417, "signal_status": "ok", "info": "Starting location: Innisfreedom Cabin — Ballintogher, Sligo. Drive to first stop: ~86 min.", "log": null, "alltrails_url": null},
  {"pos": 1, "name": "Slieve League Cliffs ⭐", "emoji": "📷", "time_label": "8:00 AM", "duration_minutes": null, "drive_override_minutes": 120, "lat": 54.6274, "lng": -8.6846, "signal_status": "none", "info": "<b>Slieve League Cliffs</b> — 601m sea cliffs, among the highest in Europe. Upper car park puts you right at the Bunglass viewpoint — arrive before 8:30am to beat the coaches. Drive up through Teelin village following signs for Upper Car Park (not lower). Fill petrol in Donegal Town before turning west — nothing reliable on the R263 coastal approach.<br><br><b>Route order:</b> Get all Bunglass shots first while the cliff is empty, then hike. Upper car park → Bunglass viewpoint (2 min). Pilgrim's", "log": "📵 NO SIGNAL — remote Donegal cliffs. Satellite device active. Download offline.\nTeelin, Co. Donegal · Bunglass Upper Car Park\nDrive from cabin: ~2 hrs via N15 north → Donegal Town → R263 west to Teelin\n⛽ Fill petrol in Donegal Town — nothing reliable past there\nParking: €15/day upper car park · Arrive before 10am while still accessible\nDrive straight through the gate before the parking attendant arrives\nUpper car park → Bunglass viewpoint: 2 min walk\nUpper car park → cove overlook (Position 2): ", "alltrails_url": "https://www.alltrails.com/explore/map/custom-route-slieve-league-viewpoint-to-cnoc-ramhar-2bf26f2?p=-1&sh=jrrmvi&utm_medium=map_share&utm_source=alltrails_virality"},
  {"pos": 2, "name": "Assaranca Waterfall", "emoji": "📷", "time_label": "2:30 PM", "duration_minutes": null, "drive_override_minutes": null, "lat": 54.7584719, "lng": -8.5135446, "signal_status": "warning", "info": "<b>Assaranca Waterfall</b> — two-tier cascade dropping into a dark plunge pool, then draining straight to Maghera Beach and the Atlantic. The gorge is narrow with overhanging vegetation — shade likely even in the afternoon, which helps enormously for long exposures. Compact location: everything you need is within a 5-minute walk of the car park.<br><br>The vegetation in late June is all mid-green and collapses to the same Zone IV–V gray in B&W — don't fight it. Let the rock faces go dark (Zone I", "log": "⚠️ PATCHY — rural Donegal, unreliable. Download offline.\nFrom Slieve League Upper Car Park: ~45min, ~40km. Route: back through Teelin → Carrick → R263 west along the coast → R230 north toward Ardara → follow signs for Assaranca / Maghera. Small free car park right at the falls.\n\nCar park → base of falls: 3 min flat walk\nCar park → left bank elevated shelf: 5 min\nMaghera Beach: 2 min below the falls\nTotal time at location: 45–60 min\n\nLight: Arrives ~2:30pm. Sun will be west-southwest — potential ", "alltrails_url": null},
  {"pos": 3, "name": "Glengesh Viewing Point", "emoji": "📷", "time_label": "3:30 PM", "duration_minutes": null, "drive_override_minutes": null, "lat": 54.7206577, "lng": -8.4844979, "signal_status": "none", "info": "<b>Glengesh Pass</b> — a glacially carved valley with steep green walls dropping away on both sides of the ridge, the road snaking down in tight hairpin bends visible from the crest. The pass itself is the road — you're shooting from pullouts, not hiking. Main viewpoint is a wide gravel shoulder on the south side as the road crests the ridge. The hairpin road is your compositional anchor — it's what makes this shot unique and must stay in frame.<br><br>The green valley walls in late June are the", "log": "📵 NO SIGNAL — remote mountain pass. Satellite device active. Download offline.\nFrom Assaranca Waterfall: ~20min, ~15km northeast via R230 → R261 through Ardara, then pass road climbs east. Main viewpoint pullout is obvious — wide gravel shoulder on the south side as the road crests the ridge.\n\nCar → viewpoint: 1 min (shooting from road shoulder)\nStep-down tree position (Shot 2): 5 min walk down from crest\nTotal time at location: 30–40 min\n\nLight: Arrives ~3:30pm. Sun west-southwest, sidelighting", "alltrails_url": null},
];

// DAY 3 — Benbulben Cluster + Mullaghmore
const DAY3_STOPS = [
  {"pos": 0, "name": "Wake Up", "emoji": "☀️", "time_label": "7:29 AM", "duration_minutes": null, "drive_override_minutes": null, "lat": 54.22781, "lng": -8.35417, "signal_status": "ok", "info": "Starting location: Innisfreedom Cabin. Drive to Gleniff: ~41 min.", "log": null, "alltrails_url": null},
  {"pos": 1, "name": "Gleniff Horseshoe — Benwiskin Drive", "emoji": "📷", "time_label": "8:30 AM", "duration_minutes": null, "drive_override_minutes": null, "lat": 54.4129132, "lng": -8.3905418, "signal_status": "none", "info": "The Gleniff Horseshoe is a spectacular 10km loop road around the base of the Dartry Mountain cliffs. Drive clockwise from the Benwiskin Centre — the road circles under near-vertical quartzite cliff walls, through a remote valley with ruined mills, schoolhouses, and cave sites. This is a drive with frequent pull-over stops, not a hike. Allow 90 minutes.", "log": "📵 NO SIGNAL — deep valley, confirmed dead zone. Satellite device active. Download offline.\nStart: The Benwiskin Centre · Eircode F91 A389 · Free roadside parking\nPhone: +353 71 917 6721\nAllTrails: The Gleniff Horseshoe – Benwiskin Trail · 8.6mi · Moderate · ~3h 33m walk / 90 min drive with stops\nDrive clockwise from Benwiskin Centre\nSingle lane road — drive slowly · Watch for sheep and oncoming traffic\nSignage poor — use offline map for navigation\nFree throughout · No entry fees\nCoffee Kart at B", "alltrails_url": "https://www.alltrails.com/trail/ireland/county-sligo/the-gleniff-horseshoe-benwiskin-trail?sh=jrrmvi&u=i&utm_medium=trail_share&utm_source=alltrails_virality"},
  {"pos": 2, "name": "Benbulben Forest Walk", "emoji": "📷", "time_label": "10:30 AM", "duration_minutes": null, "drive_override_minutes": null, "lat": 54.3618, "lng": -8.5023, "signal_status": "warning", "info": "<b>Benbulben Forest Walk</b> — Ireland's most distinctive mountain, a flat-topped limestone plateau with sheer serrated cliff faces. Three completely different shots here depending on how far you go. The geometry of that cliff edge against the sky is the defining element — nothing else in Ireland looks like this.<br><br>Shoot the approach road silhouette BEFORE you even park — pull off on the way in. Then the southwest meadow for the close pinnacle shot. Then hike 45 min if legs allow after yest", "log": "⚠️ PATCHY — forested hillside, unreliable. Download offline.\nGortarowey Forest Recreation Area · Free parking · Free entry\nAllTrails: Benbulben Forest Walk · 3.5 mi · Easy · ~1.5 hrs walk · Allow 3 hrs with camera\nStart at upper car park · Walk clockwise for best approach\nNo toilets at car park or on trail — sort before you arrive\nNo bins on trail — pack out all rubbish\nCan be windy on exposed sections · Gravel path throughout\nTrail passes through Coillte forestry — may have tree felling activit", "alltrails_url": "https://www.alltrails.com/trail/ireland/county-sligo/benbulben-forest-loop?sh=jrrmvi&u=i&utm_medium=trail_share&utm_source=alltrails_virality"},
  {"pos": 3, "name": "Mullaghmore Head + Classiebawn Castle ⭐", "emoji": "📷", "time_label": "2:00 PM", "duration_minutes": null, "drive_override_minutes": null, "lat": 54.4656066, "lng": -8.4497814, "signal_status": "ok", "info": "Mullaghmore Head is one of Ireland's most layered photography locations — the classic 300mm compression shot of Classiebawn Castle with Benbulben looming behind it, dramatic surge rock shelves along the headland loop, a secret sea cave accessible only at low tide, and some of the Atlantic's most powerful swells in Europe. Park at the harbour and drive or walk the R279 loop clockwise. Two visits planned: Day 1 (afternoon light) and Day 3 (afternoon scout + golden hour). ⚠️ Check tide tables befor", "log": "✅ SIGNAL OK — coastal village, good coverage\nPark: Mullaghmore Harbour · Free\nDrive the R279 loop clockwise · 2.8mi · ~1 hr walk or 15 min drive with pull-overs\nAllTrails: Mullaghmore Head Loop · Easy · 2.8mi · ~1 hr\nFree throughout · No entry fees\nPub + café in Mullaghmore village\n\n⚠️ SECRET CAVE: Low tide access only — check Irish tide tables for Jun 22 + Jun 24\nTide resource: www.tideschart.com/Ireland/Mullaghmore\nCave is on the northwest headland side of the loop · Look for the rock arch at ", "alltrails_url": "https://www.alltrails.com/trail/ireland/county-sligo/mullaghmore-head-loop?sh=jrrmvi&u=i&utm_medium=trail_share&utm_source=alltrails_virality"},
];

// DAY 4 — Mayo Day — Knocknarea + Downpatrick Head
const DAY4_STOPS = [
  {"pos": 0, "name": "Wake Up", "emoji": "☀️", "time_label": "6:40 AM", "duration_minutes": null, "drive_override_minutes": null, "lat": 54.22781, "lng": -8.35417, "signal_status": "ok", "info": "Starting location: Innisfreedom Cabin. Drive to Downpatrick Head: ~90 min via N59 through Ballina.", "log": null, "alltrails_url": null},
  {"pos": 1, "name": "Downpatrick Head + Dún Briste ⭐", "emoji": "📷", "time_label": "8:30 AM", "duration_minutes": null, "drive_override_minutes": null, "lat": 54.3236, "lng": -9.3439, "signal_status": "none", "info": "<b>Downpatrick Head + Dún Briste</b> — 45m isolated sea stack, 80m offshore, separated from the mainland in a storm in 1393. The layered limestone bedding — 25 million years of strata — is visible in every shot. The WW2 lookout post on the mainland cliff adds human scale and historical context. Unfenced cliff edge throughout — treat it with respect, especially with wind.<br><br><b>Sea cave access — read carefully:</b> The cave shots (Imgs 5 & 7) require descending a series of slippery ledges fro", "log": "📵 NO SIGNAL — remote Mayo headland. Satellite device active. Download offline maps.\nFree entry · Free parking (large car park, recently extended)\n⚠️ Do not leave valuables visible in car — break-ins reported\nWalk: 500m / 10 min from car park to stack viewpoint · Grass path, can be very muddy\nAllTrails: Downpatrick Head · 1.4km · Easy · ~20 min\nCoffee kiosk 'Tea by the Sea' at car park\n⚠️ NO fence at cliff edge — unguarded 40m drop · Watch bubble grass underfoot\n⚠️ No visit in wind warning condit", "alltrails_url": "https://www.alltrails.com/trail/ireland/county-mayo/downpatrick-head--2?sh=jrrmvi&u=i&utm_medium=trail_share&utm_source=alltrails_virality"},
  {"pos": 2, "name": "Aughris Head", "emoji": "📷", "time_label": "1:10 PM", "duration_minutes": 120, "drive_override_minutes": 100, "lat": 54.2724669, "lng": -8.7562016, "signal_status": "warning", "info": "Aughris Head is a rugged, largely undiscovered headland on the south shore of Sligo Bay. The clifftop loop walk passes a WWII lookout post, a cliff-edge Iron Age promontory fort, a holy well associated with St. Patrick, and the ruins of a deserted village. Views across Sligo Bay to Benbulben and Knocknarea are exceptional. Park at the Beach Bar — a traditional Irish pub at the trailhead.", "log": "⚠️ PATCHY SIGNAL — rural Sligo coast, unreliable. Download offline maps.\n⚠️ OPTIONAL STOP — after a 3hr session at Downpatrick, take this if energy allows\nAfter Aughris: ~25 min back to cabin. If time/energy remains, reshoot window available\nfor Streedagh, Glencar, Mullaghmore, or Devil's Chimney before heading home.\n\nPark: Beach Bar car park · Free · Aughris, Co. Sligo\nAllTrails: Sligo Bay Circular · 2.2 mi · Easy · ~47 min · 4.8 stars\nTrail refs: sligowalks.ie/walks/aughris · aughris.com/the-w", "alltrails_url": "https://www.alltrails.com/trail/ireland/county-sligo/sligo-bay-circular?sh=jrrmvi&u=i&utm_medium=trail_share&utm_source=alltrails_virality"},
];

// DAY 5 — Departure Morning — Sligo to Dublin
const DAY5_STOPS = [
  {"pos": 0, "name": "Wake Up", "emoji": "☀️", "time_label": "6:08 AM", "duration_minutes": null, "drive_override_minutes": null, "lat": 54.22781, "lng": -8.35417, "signal_status": "ok", "info": "Starting location: Innisfreedom Cabin — Ballintogher, Sligo. Drive to first stop: ~41 min.", "log": null, "alltrails_url": null},
  {"pos": 1, "name": "Optional Final Shoot", "emoji": "📷", "time_label": "7:00 AM", "duration_minutes": null, "drive_override_minutes": null, "lat": 54.3402, "lng": -8.3685, "signal_status": "ok", "info": "Only if conditions are spectacular. Glencar 25 min from cabin; roadside Benbulben 20 min.", "log": null, "alltrails_url": null},
  {"pos": 2, "name": "Check Out — Innisfreedom", "emoji": "🏡", "time_label": "10:00 AM", "duration_minutes": null, "drive_override_minutes": null, "lat": 54.22781, "lng": -8.35417, "signal_status": "ok", "info": "Load all gear. Return key per cabin instructions. Check-out by 11am.", "log": "✅ SIGNAL OK — cabin has WiFi\nInnisfreedom, Killerry, Ballintogher · Conf: 5869191106", "alltrails_url": null},
  {"pos": 3, "name": "Drive Dublin — N4/M4", "emoji": "🚗", "time_label": "12:00 PM", "duration_minutes": null, "drive_override_minutes": null, "lat": null, "lng": null, "signal_status": "ok", "info": "Straight shot. Drop Enterprise at Dublin Airport arrivals first, then Airlink bus or taxi to Moxy.", "log": "Enterprise return: Dublin Airport Terminal 1 · Conf: 73391556677627\nAirlink 747 bus: Airport → city centre ~30 min / €8", "alltrails_url": null},
  {"pos": 4, "name": "Check In — Moxy Dublin City", "emoji": "🏨", "time_label": "2:00 PM", "duration_minutes": null, "drive_override_minutes": null, "lat": 53.3444, "lng": -6.2672, "signal_status": "ok", "info": "James and Dad arriving. First afternoon in Dublin — easy wander, pubs, food. Plan tomorrow over dinner.", "log": "Moxy Dublin City\nPhil Conf: 99210319 · James Conf: 99222693\nJun 26–28 · 2 nights · 2 rooms (Twin each)", "alltrails_url": null},
];

// DAY 6 — Dublin — Full Day
const DAY6_STOPS = [
  {"pos": 0, "name": "Wake Up", "emoji": "☀️", "time_label": "8:32 AM", "duration_minutes": null, "drive_override_minutes": null, "lat": 53.3444, "lng": -6.2672, "signal_status": "ok", "info": "Starting location: Moxy Dublin City. Drive to first stop: ~8 min.", "log": null, "alltrails_url": null},
  {"pos": 1, "name": "Sing Street Walk — The Liberties", "emoji": "🎬", "time_label": "9:00 AM", "duration_minutes": null, "drive_override_minutes": null, "lat": 53.3308, "lng": -6.2675, "signal_status": "ok", "info": "Self-guided walk through the south Dublin filming locations. All within 20 min walk of each other.", "log": "✅ SIGNAL OK — Dublin city centre\nStart: Synge Street CBS, Dublin 8\nAll within 20 min walk in Liberties/south Dublin", "alltrails_url": null},
  {"pos": 2, "name": "Guinness Storehouse", "emoji": "🍺", "time_label": "11:00 AM", "duration_minutes": null, "drive_override_minutes": null, "lat": 53.3419, "lng": -6.2869, "signal_status": "ok", "info": "Book in advance — sells out, especially weekends. 7 floors of exhibition. Gravity Bar at the top: 360° view of Dublin over your complimentary pint.", "log": "✅ SIGNAL OK — Dublin city centre\nSt James's Gate, Dublin 8\nBook: guinness-storehouse.com", "alltrails_url": null},
  {"pos": 3, "name": "Lunch — Dudley's Bar, Thomas St", "emoji": "🍽️", "time_label": "1:30 PM", "duration_minutes": null, "drive_override_minutes": null, "lat": 53.3435, "lng": -6.2812, "signal_status": "ok", "info": "Named after Thomas 'Bang Bang' Dudley, a famous Dublin character. 28 craft beer taps, proper pub food.", "log": "48 Thomas St, The Liberties, Dublin D08 Y44A", "alltrails_url": null},
  {"pos": 4, "name": "Jameson Distillery — Bow St", "emoji": "🥃", "time_label": "2:30 PM", "duration_minutes": null, "drive_override_minutes": null, "lat": 53.3476, "lng": -6.2793, "signal_status": "ok", "info": "The original Dublin distillery in Smithfield — 15 min walk from Guinness. Book in advance. Interactive tour with whiskey tasting.", "log": "✅ SIGNAL OK — Dublin city centre\nBow St, Smithfield, Dublin 7\nBook: jamesonwhiskey.com", "alltrails_url": null},
  {"pos": 5, "name": "DART to Dalkey — Coliemore Harbour", "emoji": "🚂", "time_label": "5:00 PM", "duration_minutes": null, "drive_override_minutes": null, "lat": 53.2738, "lng": -6.1018, "signal_status": "ok", "info": "DART southbound from city center. Alight at Dalkey station, 10 min walk to Coliemore Harbour. WhatsApp Ken the Ferryman before heading down.", "log": "✅ SIGNAL OK — Dublin suburb\nDART: Tara St or Pearse → Dalkey (~35 min) · ~€4 return\nKen the Ferryman: WhatsApp +353 85 242 6516\nRuns: Apr–Sep · 10am–6pm · weather permitting\nFerry: €10/person return · Walk-up, no booking needed", "alltrails_url": null},
  {"pos": 6, "name": "Dalkey Island — Sing Street Ending", "emoji": "🎬", "time_label": "6:30 PM", "duration_minutes": null, "drive_override_minutes": null, "lat": 53.2699, "lng": -6.0933, "signal_status": "ok", "info": "The final scene of Sing Street was filmed here — Conor and Raphina's dawn escape. St Begnet's 7th century church ruins, Martello tower, feral goats, grey seals, puffins.", "log": "✅ SIGNAL OK — Dublin city centre\nKen the Ferryman: +353 85 242 6516 (WhatsApp first)\nFerry: €10/person return · 10 min crossing\nWave from jetty to call boat back", "alltrails_url": null},
  {"pos": 7, "name": "Evening — Pub / Live Music", "emoji": "🍺", "time_label": "8:30 PM", "duration_minutes": null, "drive_override_minutes": null, "lat": 53.3315, "lng": -6.2609, "signal_status": "ok", "info": "Back by DART. Whelan's on Wexford Street for legendary live music. ⚠️ EI 3226 departs 11:30am tomorrow — leave Moxy by 9:30am.", "log": "Whelan's: 25 Wexford Street, Dublin\n⚠️ Tomorrow: EI 3226 DUB→GLA 11:30am · Conf: 2FH8WF\nLeave Moxy by 9:30am", "alltrails_url": null},
];


async function migrate() {
  console.log('Adding stops for Days 2-6...');
  
  // Get day IDs from database
  const { data: days } = await supabase
    .from('days')
    .select('id, day_number')
    .eq('trip_id', TRIP_ID)
    .in('day_number', [2,3,4,5,6]);
  
  const dayMap = {};
  for (const d of days) dayMap[d.day_number] = d.id;
  
  const allStops = [
    ...DAY2_STOPS.map(s => ({...s, day_number: 2})),
    ...DAY3_STOPS.map(s => ({...s, day_number: 3})),
    ...DAY4_STOPS.map(s => ({...s, day_number: 4})),
    ...DAY5_STOPS.map(s => ({...s, day_number: 5})),
    ...DAY6_STOPS.map(s => ({...s, day_number: 6})),
  ];
  
  for (const stop of allStops) {
    const dayId = dayMap[stop.day_number];
    const { day_number, ...stopData } = stop;
    const { error } = await supabase.from('stops').insert({
      ...stopData,
      day_id: dayId,
      trip_id: TRIP_ID,
    });
    if (error) { console.error('Error inserting stop:', stop.name, error.message); }
    else console.log(`  ✅ Day ${stop.day_number}: ${stop.name}`);
  }
  
  console.log('\n✅ Done!');
}

migrate().catch(err => { console.error('Failed:', err); process.exit(1); });
